### ISSUE TITLE
Using Default Credential Provider when running on AWS

### ISSUE THREAD

**Issue by Ulberg** [lpil/bucket#3]
This is more of a question than an "issue".

What do you think about changing the implementation from using the current [aws4](https://github.com/lpil/aws4_request) package, to use a variation of the [Default Credential Provider](https://sdk.amazonaws.com/java/api/latest/software/amazon/awssdk/auth/credentials/DefaultCredentialsProvider.html).

In short, the Default Credential Provider is a class that implements the process that AWS uses to look for valid credentials to do request against other AWS services in a runtime. It is why we can call Secret Manager from a Lambda, EC2 and our local machine. It is the underpinning for making a Gleam SDK for AWS.

Any thoughts?

**Comment by lpil** [comment]
A library that does that loading would be very useful!

It should not be part of this library as there's nothing AWS specific here, and all AWS libraries would be able to use that functionality.

**Comment by lpil** [comment]
It definitely wouldn't be maintained by the core team.

This library here is maintained by me outside of the core team. I'm not an AWS user so I probably wouldn't ever make that library, I don't have any need for it.

**Comment by lpil** [comment]
If you want to implement it and get stuck do drop by the discord server where people can help.

**Comment by Ulberg** [comment]
Hi @lpil 

I took quite a while before I had any free time... Just about a year and a half, but I did end up making it into a ["full" AWS SDK](https://github.com/Ulberg/aws-gleam) based on Smithy (AWS domain model) , that both contains the needed things to run the Lambda Runtime, as well as being able to interact with any AWS service (SQS, S3, DynamoDB)

A lot of the code itself is written with AI, but I have been quite hands-on with it. I was wondering if you think that this is something of value for others? :)
